### ISSUE TITLE
UE 5.3 and Quest 3 support

### ISSUE THREAD

**Issue by JustinHoang1703** [oculus-samples/Unreal-HandPoseShowcase#2]
Hi, hope you are doing great! I just wondering if we have a plan to upgrade it to UE 5.3 and support Quest 3? I am trying to open it but it gives error due to different engine version.

**Comment by cryptoLaoBai** [comment]
I encountered errors during the build when using UE5.3 as well. Mine was the one below. What errors did you encounter?
D:\Epic Games\UE_5.3\Engine\Source\predefined C++ types (compiler internal)(420): error C2248: "FHazardPointerCollection::FHazardRecord::FHazardRecord": cannot access private member declared in class "FHazardPointerCollection::FHazardRecord"
D:\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\Experimental\Containers\HazardPointer.h(86): note: see declaration of "FHazardPointerCollection::FHazardRecord::FHazardRecord"
D:\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\Experimental\Containers\HazardPointer.h(77): note: see declaration of "FHazardPointerCollection::FHazardRecord"
D:\Epic Games\UE_5.3\Engine\Source\predefined C++ types (compiler internal)(420): note: template instantiation context (earliest instantiation context) is
D:\Epic Games\UE_5.3\Engine\Source\Runtime\Core\Public\Experimental\Containers\HazardPointer.h(133): note: see reference to function template instantiation "void __builtin_array_init_helperFHazardPointerCollection::FHazardRecord(_T *,size_t) noexcept(<expr>)" being compiled
with
[
_T=FHazardPointerCollection::FHazardRecord
]

**Comment by jasonmeisel** [comment]
Thanks for the report! For now, I recommend checking out [Unreal-HandGameplay](https://github.com/oculus-samples/Unreal-HandGameplay), which has already been ported to UE 5.
